### ISSUE TITLE
后端接口报SessionNotCreatedException，请教一下这是什么问题

### ISSUE THREAD

**Issue by gadfly3173** [cn-matsuri/matsuri_translation#97]
pm2中celery-run-error.log输出的日志：
```
[2020-04-09 09:57:46,658: INFO/MainProcess] Received task: Matsuri_translation.manager.execute_event[57f8ca99-0a41-4246-9384-f6f118ed8a0d]  
[2020-04-09 10:02:40,949: ERROR/ForkPoolWorker-1] Task Matsuri_translation.manager.execute_event[57f8ca99-0a41-4246-9384-f6f118ed8a0d] raised unexpected: SessionNotCreatedException('session not created\nfrom disconnected: received Inspector.detached event\n  (Session info: headless chrome=79.0.3945.130)', None, None)
Traceback (most recent call last):
  File "/home/gadflyFang/.local/share/virtualenvs/matsuri_translation-kPn8hfyq/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/gadflyFang/.local/share/virtualenvs/matsuri_translation-kPn8hfyq/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/matsuri_translation/Matsuri_translation/manager.py", line 44, in execute_event
    driver = webdriver.Chrome(options=chrome_options)
  File "/home/gadflyFang/.local/share/virtualenvs/matsuri_translation-kPn8hfyq/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/gadflyFang/.local/share/virtualenvs/matsuri_translation-kPn8hfyq/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/gadflyFang/.local/share/virtualenvs/matsuri_translation-kPn8hfyq/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/gadflyFang/.local/share/virtualenvs/matsuri_translation-kPn8hfyq/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/gadflyFang/.local/share/virtualenvs/matsuri_translation-kPn8hfyq/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from disconnected: received Inspector.detached event
  (Session info: headless chrome=79.0.3945.130)
```

**Comment by wudifeixue** [comment]
这个问题已经不存在了，现在可以自己用docker compose一键部署
https://github.com/cn-matsuri/TweetToaster#%E7%9B%B4%E6%8E%A5%E9%83%A8%E7%BD%B2%E9%A2%84%E6%9E%84%E5%BB%BA%E9%95%9C%E5%83%8F
